# Generated by Django 5.0.6 on 2024-05-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="name",
            field=models.CharField(
                choices=[
                    ("free_trial", "Free Trial"),
                    ("basic", "Basic"),
                    ("premium", "Premium"),
                    ("one_time_payment", "One Time Payment"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
