# Generated by Django 5.0.6 on 2024-05-18 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("system_management", "0002_package_active_alter_clinic_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExposedPermission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "permission",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="auth.permission"),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
