# Generated by Django 5.0.6 on 2024-05-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0003_exposedpermission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clinic",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="package",
            options={"ordering": ("-created_at",)},
        ),
    ]
