# Generated by Django 5.0.6 on 2024-05-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0004_alter_clinic_options_alter_package_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="capacity",
            field=models.PositiveIntegerField(default=5, verbose_name="Capacity/Hours"),
        ),
    ]
