# Generated by Django 5.0.6 on 2024-05-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0005_clinic_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="capacity",
            field=models.PositiveIntegerField(default=5, verbose_name="Patient Count Capacity/Hours"),
        ),
    ]
