# Generated by Django 5.0.6 on 2024-05-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0006_alter_clinic_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
