# Generated by Django 5.0.6 on 2024-12-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0013_clinic_profit_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clinics/logos'),
        ),
    ]
