# Generated by Django 5.0.6 on 2025-01-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0014_clinic_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='profit_share',
        ),
    ]
