# Generated by Django 5.0.6 on 2025-04-16 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system_management', '0015_remove_clinic_profit_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='limit_threshold',
            field=models.PositiveIntegerField(default=10, verbose_name='Inventory Limit Threshold'),
        ),
        migrations.AlterField(
            model_name='exposedpermission',
            name='permission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exposed_permission', to='auth.permission'),
        ),
    ]
