#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
# Apply database migrations
python manage.py migrate
# Collect static files
python manage.py collectstatic --noinput
# Start server
exec python manage.py runserver 0.0.0.0:8000
