version: '3.8'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  locale: {}
  media: {}
services:
  django: &django
    image: telasttechnologies/clinic_django:latest
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host # only accessible form localhost, access through 443 port on reverse proxy
    depends_on:
      - postgres
      - redis
    volumes:
     - locale:/app/locale
     - media:/app/media/
    env_file:
      - ./docker/.envs/.production/.django
      - ./docker/.envs/.production/.postgres
    command: /start

  postgres:
    image: telasttechnologies/clinic_postgres:main
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./docker/.envs/.production/.postgres