version: "3"

volumes:
  clinic_production_postgres_data: {}
  clinic_production_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    image: clinic_production_django
    container_name: clinic_production_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./docker/.envs/.production/.django
      - ./docker/.envs/.production/.postgres
    environment:
      - OPENBLAS_NUM_THREADS=1
    ports:
      - "8080:8080"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./docker/production/postgres/Dockerfile
    image: clinic_production_postgres
    container_name: clinic_production_postgres
    volumes:
      - clinic_production_postgres_data:/var/lib/postgresql/data
      - clinic_production_postgres_data_backups:/backups
    env_file:
      - ./docker/.envs/.production/.postgres
