version: '3.8'

services:
  django: &django
    image: telasttechnologies/clinic_django:main
    container_name: django-clinic
    networks:
      - nginx_default
    depends_on:
      - postgres
    volumes:
     - locale:/app/locale
     - media:/app/media/
     - static: /app/static
     - staticfiles: /app/staticfiles
    env_file:
      - ./docker/.envs/.production/.django
      - ./docker/.envs/.production/.postgres
    command: /start

  postgres:
    image: telasttechnologies/clinic_postgres:main
    container_name: postgres-clinic
    networks:
      - nginx_default
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./docker/.envs/.production/.postgres


volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  locale: {}
  media: {}
  static: {}
  staticfiles: {}

networks:
  nginx_default:
    external: true
