version: '3.8'

services:
  django:
    image: telasttechnologies/clinic_django:main
    container_name: django-clinic
    networks:
      - nginx_default
    depends_on:
      - postgres
    volumes:
     - clinic_locale:/app/locale/
     - clinic_media:/app/media/
     - clinic_static:/app/static/
     - clinic_staticfiles:/app/staticfiles/
    env_file:
      - ./docker/.envs/.qa/.django
      - ./docker/.envs/.qa/.postgres
    command: /start

  postgres:
    image: telasttechnologies/clinic_postgres:main
    container_name: postgres-clinic
    networks:
      - nginx_default
    ports:
      - "5433:5432"  # Host port:Container port
    volumes:
      - clinic_postgres_data:/var/lib/postgresql/data
      - clinic_postgres_data_backups:/backups
    env_file:
      - ./docker/.envs/.qa/.postgres

volumes:
  clinic_postgres_data: {}
  clinic_postgres_data_backups: {}
  clinic_locale: {}
  clinic_media: {}
  clinic_static: {}
  clinic_staticfiles: {}

networks:
  nginx_default:
    external: true
