version: '3.8'

services:
  django: &django
    image: telasttechnologies/clinic_django:main
    container_name: django-clinic
    networks:
      - nginx_default
    depends_on:
      - postgres
    volumes:
     - locale:/app/locale/
     - media:/app/media/
     - static:/app/static/
     - staticfiles:/app/staticfiles/
    environment:
      - ENV=qa
      - USE_DOCKER=yes
      - IPYTHONDIR=${IPYTHONDIR}
      - INTERNAL_IPS=${INTERNAL_IPS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - FERNET_KEY=${FERNET_KEY}
      - PASSWORD_RESET_CONFIRM_REDIRECT_BASE_URL=${PASSWORD_RESET_CONFIRM_REDIRECT_BASE_URL}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - BREVO_API_URL=${BREVO_API_URL}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

    command: /start

  postgres:
    image: telasttechnologies/clinic_postgres:main
    container_name: postgres-clinic
    networks:
      - nginx_default
    volumes:
      - qa_postgres_data:/var/lib/postgresql/data
      - qa_postgres_data_backups:/backups
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  qa_postgres_data: {}
  qa_postgres_data_backups: {}
  locale: {}
  media: {}
  static: {}
  staticfiles: {}

networks:
  nginx_default:
    external: true
