# Generated by Django 5.0.6 on 2024-05-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patientreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientreport",
            name="document",
            field=models.FileField(upload_to="media/patients/reports"),
        ),
    ]
