# Generated by Django 5.0.6 on 2024-05-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientreport_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='document',
            field=models.FileField(upload_to='patients/reports'),
        ),
    ]
