# Generated by Django 5.0.6 on 2024-07-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_uid_alter_patientreport_uid_squashed_0009_alter_patient_uid_alter_patientreport_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='channel',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('telegram', 'Telegram'), ('whatsapp', 'Whatsapp'), ('sms', 'SMS'), ('email', 'Email'), ('other', 'Other')], default='facebook', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='nid',
            field=models.CharField(default=29909011304572, max_length=100),
            preserve_default=False,
        ),
    ]
