# Generated by Django 5.0.6 on 2024-10-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_patient_email_patient_unique_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nid',
            field=models.CharField(help_text='National/Passport ID', max_length=100),
        ),
    ]
