# Generated by Django 5.0.6 on 2024-10-20 21:11

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_patient_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medical_number',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, help_text='medical number', include_alpha=False, length=16, unique=True),
        ),
    ]
