# Generated by Django 5.0.6 on 2024-12-29 09:38

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_patient_medical_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=django_countries.fields.CountryField(default='EG', max_length=2),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='passport',
            field=models.CharField(default='', help_text='Passport ID', max_length=14),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='channel',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin'), ('youtube', 'Youtube'), ('tiktok', 'Tiktok'), ('snapchat', 'Snapchat'), ('telegram', 'Telegram'), ('whatsapp', 'Whatsapp'), ('sms', 'SMS'), ('email', 'Email'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nid',
            field=models.CharField(default='', help_text='National ID', max_length=14),
        ),
    ]
