# Generated by Django 5.0.6 on 2024-12-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_alter_patient_medical_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='passport',
            field=models.CharField(default='', help_text='Passport ID', max_length=10),
        ),
    ]
