# Generated by Django 5.0.6 on 2024-12-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_alter_patient_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nid',
            field=models.CharField(blank=True, default='', help_text='National ID', max_length=14),
        ),
        migrations.AlterField(
            model_name='patient',
            name='passport',
            field=models.CharField(blank=True, default='', help_text='Passport ID', max_length=10),
        ),
    ]
