# Generated by Django 5.0.6 on 2025-04-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_patientprescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='other_channel',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
