# Generated by Django 5.0.6 on 2025-05-20 11:04

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_patient_other_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='EG'),
        ),
    ]
