# Generated by Django 5.0.6 on 2025-06-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_alter_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
