# Generated by Django 5.0.6 on 2024-05-21 18:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("system_management", "0004_alter_clinic_options_alter_package_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("charge", models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ("active", models.BooleanField(default=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="system_management.clinic",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "unique_together": {("clinic", "name")},
            },
        ),
    ]
