# Generated by Django 5.0.6 on 2024-06-24 01:16

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='uid',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
