# Generated by Django 5.0.6 on 2024-12-30 04:47

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0007_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='no',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, help_text='Service number', include_alpha=False, length=6, unique=True),
        ),
    ]
