# Generated by Django 5.0.6 on 2024-05-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_staff_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="is_client_admin",
            field=models.BooleanField(default=False, verbose_name="Client Admin"),
        ),
    ]
