# Generated by Django 5.0.6 on 2024-05-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_alter_staff_is_client_admin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={"ordering": ("-created_at",), "permissions": (("change_clinic", "Can Change Clinic"),)},
        ),
    ]
