# Generated by Django 5.0.6 on 2024-06-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staff_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('-created_at',), 'permissions': (('change_clinic', 'Can Change Clinic'),), 'verbose_name_plural': 'Staff'},
        ),
    ]
