# Generated by Django 5.0.6 on 2024-09-30 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_staff_uid_squashed_0011_alter_staff_uid'),
        ('system_management', '0008_alter_clinic_uid_alter_exposedpermission_uid_and_more_squashed_0012_alter_clinic_uid_alter_exposedpermission_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='clinic',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='system_management.clinic'),
        ),
    ]
