# Generated by Django 5.0.6 on 2024-10-20 21:11

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_staff_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_id',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, help_text='Staff Code number', include_alpha=False, length=16, unique=True),
        ),
    ]
