# Generated by Django 5.0.6 on 2025-05-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_alter_staff_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('call_center', 'Call Center')], default='admin', max_length=50),
        ),
    ]
