# Generated by Django 5.0.6 on 2024-06-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sub_total',
            field=models.PositiveIntegerField(default=0, help_text='Total without tax and discount'),
        ),
    ]
