# Generated by Django 5.0.6 on 2024-12-30 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_chargeitem_uid_alter_chargeservice_uid_and_more_squashed_0008_alter_chargeitem_uid_alter_chargeservice_uid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargeItem',
        ),
    ]
