# Generated by Django 5.0.6 on 2024-12-30 04:14

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_initial'),
        ('invoices', '0009_delete_chargeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_items', to='invoices.invoice')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_items', to='inventory.supply')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('invoice', 'supply')},
            },
        ),
    ]
