# Generated by Django 5.0.6 on 2024-12-31 10:38

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_chargeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='no',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, help_text='Invoice number', include_alpha=False, length=6, unique=True),
        ),
    ]
