# Generated by Django 5.0.6 on 2025-01-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_invoice_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL_PAID', 'Partial Paid'), ('UNPAID', 'Unpaid'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=20),
        ),
    ]
