# Generated by Django 5.0.6 on 2025-01-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial_paid', 'Partial Paid'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled')], default='unpaid', max_length=20),
        ),
    ]
