# Generated by Django 5.0.6 on 2025-01-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/signatures'),
        ),
    ]
