# Generated by Django 5.0.6 on 2024-05-23 10:04

import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0001_initial"),
        ("patients", "0002_patientreport"),
        ("visits", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("booked", "Booked"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="booked",
                        max_length=20,
                        protected=True,
                    ),
                ),
                ("scheduled", models.BooleanField(default=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="visits", to="patients.patient"
                    ),
                ),
                ("services", models.ManyToManyField(related_name="visits", to="healthcare.service")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
