# Generated by Django 5.0.6 on 2024-05-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0005_alter_visit_status_squashed_0011_chargeitem_chargeservice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chargeitem",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="chargeservice",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="visit",
            options={"ordering": ("-created_at",)},
        ),
    ]
