# Generated by Django 5.0.6 on 2024-05-24 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0001_initial"),
        ("inventory", "0005_supply_qrcode"),
        ("visits", "0012_alter_chargeitem_options_alter_chargeservice_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargeitem",
            name="supply",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="charge_items", to="inventory.supply"
            ),
        ),
        migrations.AlterField(
            model_name="chargeservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="charge_services", to="healthcare.service"
            ),
        ),
    ]
