# Generated by Django 5.0.6 on 2024-05-25 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_alter_patientreport_document"),
        ("visits", "0013_alter_chargeitem_supply_alter_chargeservice_service"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="visit",
            unique_together={("patient", "date")},
        ),
    ]
