# Generated by Django 5.0.6 on 2024-05-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_visit_squashed_0015_remove_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('checked_in', 'Checked In'), ('financially_cleared', 'Financially Cleared'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
