# Generated by Django 5.0.6 on 2024-06-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0016_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
