# Generated by Django 5.0.6 on 2024-06-07 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0017_visit_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chargeservice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chargeservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='chargeservice',
            name='visit',
        ),
        migrations.DeleteModel(
            name='ChargeItem',
        ),
        migrations.DeleteModel(
            name='ChargeService',
        ),
    ]
