# Generated by Django 5.0.6 on 2024-10-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0020_alter_visit_uid_squashed_0024_alter_visit_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
