# Generated by Django 5.0.6 on 2024-12-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0025_alter_visit_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
