# Generated by Django 5.0.6 on 2024-12-31 04:53

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0026_alter_visit_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='no',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, help_text='Visit number', include_alpha=False, length=6, unique=True),
        ),
    ]
