# Generated by Django 5.0.6 on 2025-04-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0027_visit_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='queue',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('checked_in', 'Checked In'), ('arrived', 'Arrived'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
