# Generated by Django 5.0.6 on 2025-04-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0028_visit_queue_alter_visit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='queue',
        ),
    ]
