# Generated by Django 5.0.6 on 2025-04-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0029_remove_visit_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='arrival_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
