# Generated by Django 5.0.6 on 2024-05-21 19:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("system_management", "0004_alter_clinic_options_alter_package_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supply",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("invoice", models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ("item", models.CharField(max_length=255)),
                ("charge", models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                (
                    "profit_share",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ]
                    ),
                ),
                ("unit_cost", models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ("quantity", models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                (
                    "clinic",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplies",
                        to="system_management.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "supplies",
                "ordering": ("-created_at",),
            },
        ),
    ]
