# Generated by Django 5.0.6 on 2024-05-21 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supply",
            name="charge",
        ),
    ]
