# Generated by Django 5.0.6 on 2024-05-21 23:51

import django.core.validators
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_supply_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="supply",
            name="charge",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("unit_cost"), "*", models.F("quantity")
                ),
                output_field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
            ),
        ),
    ]
