# Generated by Django 5.0.6 on 2024-05-23 06:30

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_supply_unit_sales_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="supply",
            name="qrcode",
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=160, unique=True),
        ),
    ]
