# Generated by Django 5.0.6 on 2024-06-24 01:14

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_supply_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='uid',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
