# Generated by Django 5.0.6 on 2024-12-30 03:43

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_supply_uid_squashed_0010_alter_supply_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='supply',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supply',
            name='lot',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, help_text='Lot number', include_alpha=False, length=8),
        ),
        migrations.AddField(
            model_name='supply',
            name='no',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, help_text='Supply number', include_alpha=False, length=6),
        ),
    ]
