# Generated by Django 5.0.6 on 2024-12-30 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_supply_description_supply_expires_at_supply_lot_and_more'),
        ('invoices', '0009_delete_chargeitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supply',
        ),
    ]
