# Generated by Django 5.0.6 on 2024-12-30 04:14

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0012_delete_supply'),
        ('system_management', '0013_clinic_profit_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('no', django_extensions.db.fields.RandomCharField(blank=True, editable=False, help_text='Supply number', include_alpha=False, length=6, unique=True)),
                ('invoice', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('item', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('supply_type', models.CharField(choices=[('drug', 'Drug'), ('supplement', 'Supplement')], max_length=10)),
                ('unit_cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('charge', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('unit_cost'), '*', models.F('quantity')), output_field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]))),
                ('lot', django_extensions.db.fields.RandomCharField(blank=True, editable=False, help_text='Lot number', include_alpha=False, length=8, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('qrcode', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=160, unique=True)),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='system_management.clinic')),
            ],
            options={
                'verbose_name_plural': 'supplies',
                'ordering': ('-created_at',),
            },
        ),
    ]
