# Generated by Django 5.0.6 on 2024-12-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
