# Generated by Django 5.0.6 on 2024-05-18 14:46

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("system_management", "0002_package_active_alter_clinic_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JoinRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("administrator_first_name", models.CharField(max_length=100)),
                ("administrator_last_name", models.CharField(max_length=100)),
                ("administrator_email", models.EmailField(max_length=254)),
                ("administrator_phone", phonenumber_field.modelfields.PhoneNumberField(max_length=128, region="EG")),
                ("clinic_name", models.CharField(max_length=100)),
                ("clinic_description", models.TextField(blank=True, null=True)),
                ("clinic_address", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "clinic_phone",
                    phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region="EG"),
                ),
                ("clinic_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("clinic_website", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="system_management.package",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
