# Generated by Django 5.0.6 on 2024-05-18 15:01

import clinic.system_management.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0001_initial"),
        ("system_management", "0002_package_active_alter_clinic_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joinrequest",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_requests",
                to="system_management.package",
                validators=[clinic.system_management.validators.PackageActiveStatusValidator()],
            ),
        ),
    ]
