# Generated by Django 5.0.6 on 2024-06-24 01:17

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_alter_joinrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='uid',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
