name: Lint and Test

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  IMAGE_NAME: ${{ vars.DOCKER_REGISTRY }}/clinic_django
  DJANGO_ENV: ${{ vars.DJANGO_ENV }} # This should be different per environment but the GitHub plan doesn't support environments

on:
  pull_request:
    branches: ['main']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  pytest:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Start Clean
        run: docker compose -f docker-compose-local.yml down -v

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build
        run: |
          docker buildx create --use --name builder --driver docker-container
          docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache --tag ${{ env.IMAGE_NAME }} -f docker-compose-local.yml .

      - name: Run Django Tests
        run: docker compose -f docker-compose-local.yml run django coverage run -m pytest

      - name: Run Check Coverage Percentage
        run: docker compose -f docker-compose-local.yml run django coverage report --fail-under=100

      - name: Tear Down
        run: docker compose -f docker-compose-local.yml down -v
