name: Lint and Test

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  IMAGE_NAME: ${{ vars.DOCKER_REGISTRY }}/clinic_django
  DJANGO_ENV: ${{ vars.DJANGO_ENV }} # This should be different per environment but the github plan doens't support environments

on:
  pull_request:
    branches: ['main']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      # Consider using pre-commit.ci for open source project
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  # With no caching at all the entire ci process takes 4m 30s to complete!
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Start Clean
        run: docker compose -f docker-compose-local.yml down -v

      - name: Build
        run: docker compose -f docker-compose-local.yml build

      - name: Run Django Tests
        run: docker compose -f docker-compose-local.yml run django coverage run -m pytest

      - name: Run Check Coverage Percentage
        run: docker compose -f docker-compose-local.yml run django coverage report --fail-under=100

      - name: Tear Down
        run: docker compose -f docker-compose-local.yml down -v
